services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Galironfydar\OllamaBundle\Service\OllamaService:
        arguments:
            $httpClient: '@http_client'
            $baseUrl: '%ollama.base_url%'